#!/bin/bash
# Fail build if any command fails
set -e
shopt -s dotglob

# Makes Appwrite-defined function/site vars available to `flutter build` via
# --dart-define-from-file, without touching the deployment's buildCommand (a
# custom `sh build.sh` must keep working unmodified). Vars are merged into
# dart_defines.json in a well-known temp path; a `flutter` wrapper is placed
# earlier on PATH so the flag reaches `flutter build` however it's invoked,
# including from inside a user script.
#
# OPEN_RUNTIMES_ENV already carries the production/development mode string
# (see docker/base-before.dockerfile) for every runtime, so it can't double as
# a vars payload. OPEN_RUNTIMES_BUILD_VARS (a JSON object of Appwrite vars) is
# the dedicated channel for this — the executor must populate it separately;
# nothing about this hook assumes it's set.

OPR_DEFINES_DIR="/usr/local/build/.open-runtimes"
OPR_DEFINES_FILE="$OPR_DEFINES_DIR/dart_defines.json"
OPR_WRAPPER_DIR="/usr/local/opr-wrappers"

mkdir -p "$OPR_DEFINES_DIR"

dart /usr/local/server/hooks/merge_dart_defines.dart "dart_defines.json" "$OPR_DEFINES_FILE"

if [ ! -f "$OPR_DEFINES_FILE" ]; then
	# No Appwrite vars and no user dart_defines.json — nothing to inject.
	opr_log "No dart-defines found, skipping flutter wrapper."
	return 0
fi

if ! REAL_FLUTTER="$(command -v flutter)"; then
	opr_error "flutter not found on PATH, skipping dart-defines injection."
	return 0
fi

mkdir -p "$OPR_WRAPPER_DIR"

cat >"$OPR_WRAPPER_DIR/flutter" <<EOF
#!/bin/bash
# Generated by build-prepare.sh. Shadows the real flutter binary so that
# --dart-define-from-file reaches "flutter build ..." however the user's
# buildCommand invokes it (directly, or from inside their own script).
if [ "\$1" = "build" ]; then
	exec "$REAL_FLUTTER" "\$@" --dart-define-from-file="$OPR_DEFINES_FILE"
fi
exec "$REAL_FLUTTER" "\$@"
EOF
chmod +x "$OPR_WRAPPER_DIR/flutter"

export PATH="$OPR_WRAPPER_DIR:$PATH"

opr_log "Injecting dart-defines via $OPR_DEFINES_FILE"
