#!/bin/bash
# Fail build if any command fails
set -e
shopt -s dotglob

# Shadows flutter on PATH so --dart-define-from-file reaches `flutter build`
# without touching the deployment's buildCommand.

OPR_DEFINES_DIR="/usr/local/build/.open-runtimes"
OPR_DEFINES_FILE="$OPR_DEFINES_DIR/dart_defines.json"
OPR_WRAPPER_DIR="/usr/local/opr-wrappers"

mkdir -p "$OPR_DEFINES_DIR"

# Build a JSON object from the keys listed in OPEN_RUNTIMES_BUILD_KEYS,
# looking each value up from the container's own env.
OPR_APPWRITE_JSON="{}"
if [ -n "${OPEN_RUNTIMES_BUILD_KEYS:-}" ]; then
	OPR_APPWRITE_JSON="$(
		read -r -a OPR_KEYS <<<"$OPEN_RUNTIMES_BUILD_KEYS"
		for opr_key in "${OPR_KEYS[@]}"; do
			opr_key="$(echo "$opr_key" | xargs)"
			[ -z "$opr_key" ] && continue
			[[ "$opr_key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { opr_error "Skipping invalid env var name: $opr_key" >&2; continue; }
			jq -n --arg k "$opr_key" --arg v "${!opr_key:-}" '{($k): $v}'
		done | jq -s 'add // {}'
	)"
fi

# Write Appwrite vars to our defines file. Always (re)write it so a build
# with no vars this time doesn't inherit a stale file from a previous build.
# The deployment's own dart_defines.json, if any, is passed to Flutter as a
# second --dart-define-from-file below — no merging needed here, Flutter
# resolves conflicts between multiple files itself.
echo "$OPR_APPWRITE_JSON" >"$OPR_DEFINES_FILE"

REAL_FLUTTER="$(command -v flutter)"

mkdir -p "$OPR_WRAPPER_DIR"

cat >"$OPR_WRAPPER_DIR/flutter" <<EOF
#!/bin/bash
# Generated by build-prepare.sh
if [ "\$1" = "build" ]; then
	if [ -f "dart_defines.json" ]; then
		exec "$REAL_FLUTTER" "\$1" "\$2" --dart-define-from-file="$OPR_DEFINES_FILE" --dart-define-from-file="dart_defines.json" "\${@:3}"
	else
		exec "$REAL_FLUTTER" "\$1" "\$2" --dart-define-from-file="$OPR_DEFINES_FILE" "\${@:3}"
	fi
fi
exec "$REAL_FLUTTER" "\$@"
EOF
chmod +x "$OPR_WRAPPER_DIR/flutter"

export PATH="$OPR_WRAPPER_DIR:$PATH"

opr_log "Injecting dart-defines via $OPR_DEFINES_FILE"
