#!/bin/bash
# Fail build if any command fails
set -e
shopt -s dotglob

# Shadows flutter on PATH so --dart-define-from-file reaches `flutter build`
# without touching the deployment's buildCommand. OPEN_RUNTIMES_ENV is already
# the production/development mode string, so vars come via OPEN_RUNTIMES_BUILD_VARS.

OPR_DEFINES_DIR="/usr/local/build/.open-runtimes"
OPR_DEFINES_FILE="$OPR_DEFINES_DIR/dart_defines.json"
OPR_WRAPPER_DIR="/usr/local/opr-wrappers"

mkdir -p "$OPR_DEFINES_DIR"

dart /usr/local/server/hooks/merge_dart_defines.dart "dart_defines.json" "$OPR_DEFINES_FILE"

if [ ! -f "$OPR_DEFINES_FILE" ]; then
	# No Appwrite vars and no user dart_defines.json — nothing to inject.
	opr_log "No dart-defines found, skipping flutter wrapper."
	return 0
fi

if ! REAL_FLUTTER="$(command -v flutter)"; then
	opr_error "flutter not found on PATH, skipping dart-defines injection."
	return 0
fi

mkdir -p "$OPR_WRAPPER_DIR"

cat >"$OPR_WRAPPER_DIR/flutter" <<EOF
#!/bin/bash
# Generated by build-prepare.sh
if [ "\$1" = "build" ]; then
	exec "$REAL_FLUTTER" "\$@" --dart-define-from-file="$OPR_DEFINES_FILE"
fi
exec "$REAL_FLUTTER" "\$@"
EOF
chmod +x "$OPR_WRAPPER_DIR/flutter"

export PATH="$OPR_WRAPPER_DIR:$PATH"

opr_log "Injecting dart-defines via $OPR_DEFINES_FILE"
