name: Version auditor

on:
  workflow_dispatch:

jobs:
  analyze-runtimes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: |
          cd .github/workflows/version-audit
          bun install
      
      - name: Run runtime analysis
        run: |
          cd .github/workflows/version-audit
          bun run start